---
title: "Preliminary analysis"
output: html_notebook
---

```{r}
library(tidyverse)
library(nlme)
library(broom)

```

Bring in the data.

```{r}
d <- read_tsv("liwc/liwc_w_meta.tsv")

```

Gotta get rid of multiple pubs in same year for same author. I use a random number to select one work per year per author.

```{r}
set.seed(12345)
d <- d |>
  rowwise() |> 
  mutate(rand_num = runif(1, 0, 1),
         author = hathi_author) |> 
  arrange(author, firstpub, rand_num) |> 
  group_by(author, firstpub) |> 
  slice(1) |> 
  ungroup()

```

Explicitly pulling out the means, limiting to 1900-2000 (for sample size), and keeping only authors with 3+ works.

```{r}
d <- d |> 
  group_by(author) |> 
  ungroup() |> 
  filter(firstpub < 2001 & firstpub > 1899) |> 
  filter(authof3ormore == TRUE)
  

```

## FW example

```{r}
library(plm)
library(ggeffects)
library(apcR)

width <- 5  # just to "thicken" up the data

# prep data
dd <- d |> 
  select(author, relig, authorage, firstpub, birthyear) |> 
  mutate(y = (relig - mean(relig)) / sd(relig),
         age = floor(authorage/width)*width,
         period = floor(firstpub/width)*width,
         cohort = floor(birthyear/width)*width,
         a = factor(age),
         p = factor(period),
         c = factor(cohort))

# get alpha_hat estimate from FE
alphaest <- plm(y ~ authorage,
                data = dd,
                effect = "twoways",
                model = "within",
                index = c("author", "firstpub"))

alphahat <- coef(alphaest)


# APC results
results <- runapc(y=y, a=a, p=p, c=c, data=dd)

model.full <- results[["model.full"]] # full APC model with theta1, theta2, and APC nonlinearities

theta1 <- results[["thetas"]][1] # theta1 = alpha + pi (age slope + period slope)
theta2 <- results[["thetas"]][2] # theta2 = gamma + pi (cohort slope + period slope)

# graph

# using a 2D-APC graph to visualize the canonical solution line
twodapc(theta1=theta1, theta=theta2, by.ticks = 0.2,
        agelimits=c(-1,1), periodlimits=c(-1, 1), cohortlimits=c(-1, 3),
        rect.bounds = c(age=F, period=F, cohort=F), combined.rect=F,
        apc.bounds=c(age=c(-Inf, Inf), period= c(-Inf, Inf), cohort= c(-Inf, Inf)),
        main.title="Canonical Solution Line")

## Adding some reference lines:
abline(h=0, col="black", lty=2) # age-zero line (i.e., line when alpha=0)
abline(h=((-1)*(theta2-theta1)), col="black", lty=2) # period-zero line (i.e., line when pi=0)
abline(v=0, col="black", lty=2) # gamma-zero line (i.e., line when gamma=0)
```

```{r}
#### (4) Displaying the Nonlinear Effects (i.e., Deviations)  ####
# ************************************************************************************** #

# showing the nonlinear effcts (or deviations)
point.effects(alpha=0, pi=0, gamma=0, results=results,
              ylim.age = c(-2, 2), 
              ylim.period = c(-2, 2),
              ylim.cohort = c(-2, 2), 
              xlim.age = c(18,94),
              xlim.period = c(1900,2000),
              xlim.cohort = c(1825,1966),
              show.intercept=TRUE)

# grabbing the nonlinear effects
AgeDeviations <- results[["AgeDeviations"]]
PeriodDeviations <- results[["PeriodDeviations"]]
CohortDeviations <- results[["CohortDeviations"]]

# inspecting the nonlinear effects
print(AgeDeviations)
print(PeriodDeviations)
print(CohortDeviations)
```

```{r}
# what happens if we assume that we can use our FE estimate?
slopes <- find.slopes(theta1, theta2, alpha=alphahat)
print(slopes)

# linear effects given assumed constraint
alpha.slope <- slopes[which(slopes$Parameter=="alpha"),"Slopes"]
pi.slope <- slopes[which(slopes$Parameter=="pi"),"Slopes"]
gamma.slope <- slopes[which(slopes$Parameter=="gamma"),"Slopes"]

# displaying the temporal effects given the constraint
point.effects(alpha=alpha.slope, pi=pi.slope, gamma=gamma.slope, results=results,
              ylim.age = c(-1, 1), 
              ylim.period = c(-1, 1),
              ylim.cohort = c(-1, 1), 
              xlim.age = c(18,94),
              xlim.period = c(1900,2000),
              xlim.cohort = c(1825,1966),
              show.intercept=TRUE)

```

```{r}
# plotting assumed linear effects on the 2D-APC graph
twodapc(theta1=theta1, theta=theta2, by.ticks = 0.2,
        agelimits=c(-1,1), periodlimits=c(-1, 1), cohortlimits=c(-1, 3),
        rect.bounds = c(age=F, period=F, cohort=F), combined.rect=F,
        apc.bounds=c(age=c(-Inf, Inf), period= c(-Inf, Inf), cohort= c(-Inf, Inf)),
        main.title="Point Identification: Verbal Ability")

## Adding some reference lines:
abline(h=0, col="black", lty=2) # age-zero line (i.e., line when alpha=0)
abline(h=((-1)*(theta2-theta1)), col="black", lty=2) # period-zero line (i.e., line when pi=0)
abline(v=0, col="black", lty=2) # cohort-zero line (i.e., line when gamma=0)

# placing point in the parameter space corresponding to assumed linear effects
points(x=pi.slope, y=alpha.slope, pch=16, col="black") # location of assumed linear effects
text(x=pi-0.2, y=alpha.slope, labels=c("Assumed \n Linear Effects"), cex=0.6) # accompanying text

```
